library(base)
library(tmvtnorm)
library(glasso)
library(simone)
library(Matrix)
library(snow)

setwd("C:/Users/Pariya/Desktop/crucialCommands/Codes/Code")
#setwd("~/Github/PariyaCode")
data <- read.csv("tests/test_data.txt",sep="\t")
source("R/gnet.R")
source("R/calculate.cutoffs.R")
source("R/calculate.lower.upper.R")
source("R/calculate.R.R")
#results <- gnet(data,1,1,1)

results <- gnet(data,2,1,1,n.cores=2)
